/// Flutter icons My
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  My
///      fonts:
///       - asset: fonts/My.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class My {
  My._();

  static const _kFontFam = 'My';

  static const IconData pill = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData doctor = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData clipboard = const IconData(0xe802, fontFamily: _kFontFam);
}
